"""
Upstox Token Manager — daily OAuth2 token refresh
Upstox access tokens expire daily at midnight IST.
This module handles storing and refreshing them automatically.
"""
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

import httpx

log = logging.getLogger("token_manager")

TOKEN_FILE = Path(__file__).parent / "upstox_token.json"  # gitignored
UPSTOX_TOKEN_URL = "https://api.upstox.com/v2/login/authorization/token"


def _load_token_file() -> dict:
    if TOKEN_FILE.exists():
        try:
            return json.loads(TOKEN_FILE.read_text())
        except Exception:
            pass
    return {}


def _save_token_file(data: dict):
    TOKEN_FILE.write_text(json.dumps(data, indent=2))
    log.info("Token saved to file")


def _is_token_valid(token_data: dict) -> bool:
    """Check if access token is still valid (not expired)."""
    if not token_data.get("access_token"):
        return False
    expires_at = token_data.get("expires_at")
    if not expires_at:
        return False
    try:
        expiry = datetime.fromisoformat(expires_at)
        # Add buffer — refresh 5 minutes before actual expiry
        now = datetime.now(timezone.utc)
        return now < expiry
    except Exception:
        return False


async def ensure_valid_token() -> str | None:
    """
    Return a valid Upstox access token.
    Checks file cache first, then env var.
    If expired, tries to refresh using refresh token.
    """
    # 1. Try token file (generated by initial auth flow)
    token_data = _load_token_file()
    if _is_token_valid(token_data):
        return token_data["access_token"]

    # 2. Try env var (set manually after Upstox auth)
    env_token = os.environ.get("UPSTOX_ACCESS_TOKEN", "")
    if env_token:
        # Store it with a default expiry assumption (6:30 AM IST next day)
        log.info("Using UPSTOX_ACCESS_TOKEN from environment")
        return env_token

    # 3. Try to refresh using refresh token
    refresh_token = token_data.get("refresh_token") or os.environ.get("UPSTOX_REFRESH_TOKEN", "")
    if refresh_token:
        new_token = await _refresh_token(refresh_token)
        if new_token:
            return new_token

    log.error(
        "No valid Upstox access token found!\n"
        "Steps to fix:\n"
        "1. Visit http://localhost:8000/api/v1/auth/upstox to authorize\n"
        "2. Or set UPSTOX_ACCESS_TOKEN in your .env file"
    )
    return None


async def _refresh_token(refresh_token: str) -> str | None:
    """Attempt to refresh expired Upstox access token."""
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            response = await client.post(
                UPSTOX_TOKEN_URL,
                data={
                    "code": refresh_token,
                    "client_id": os.environ["UPSTOX_API_KEY"],
                    "client_secret": os.environ["UPSTOX_API_SECRET"],
                    "redirect_uri": os.environ["UPSTOX_REDIRECT_URI"],
                    "grant_type": "authorization_code",
                },
                headers={"Accept": "application/json"},
            )
            if response.status_code == 200:
                data = response.json()
                token_data = {
                    "access_token": data["access_token"],
                    "refresh_token": data.get("refresh_token", refresh_token),
                    "expires_at": data.get("expires_in"),  # seconds from now
                }
                _save_token_file(token_data)
                log.info("Token refreshed successfully")
                return token_data["access_token"]
            else:
                log.error(f"Token refresh failed: {response.status_code}")
    except Exception as e:
        log.error(f"Token refresh error: {e}")
    return None
